/**
 * Diagnosis Engine
 * Orchestrates the embedding-based diagnostic pipeline
 * 
 * Code file generated by Claude Haiku 4.5 based on the following prompt:
 * "Implement a debugger file in TypeScript that orchestrates the process of diagnosing a student's stuck type based on their responses to diagnostic questions. The engine should compute an embedding vector from the student's answers, use a logistic regression classifier to predict the stuck type, apply any behavioral signal boosts, and return a ranked list of stuck types with confidence scores. Include error handling and logging for each step of the process."
 * 
 */

import {
  computeEmbeddingVector,
  computeEmbeddingScores,
  applyBehavioralSignalBoosts,
} from "./wordEmbedding";
import { classifyWithLogisticRegression } from "./logisticRegression";
import { blendScores } from "./weights";
import type {
  DiagnosticAnswers,
  DiagnosisResult,
  StuckType,
  DiagnosticContext,
} from "./types";

/**
 * Main diagnostic function - EMBEDDINGS ONLY
 * 1. Computes embedding vector [a, b, c, ...] from responses
 * 2. Logistic Regression classifier turns vector into stuck type prediction
 * 3. Returns softmax-normalized scores (sum to 100%) + summary
 */
export async function diagnoseWithHybridModel(
  answers: DiagnosticAnswers,
  context?: DiagnosticContext,
): Promise<DiagnosisResult> {
  try {
    // Safety check: validate answers before processing
    if (!answers || typeof answers !== 'object') {
      throw new Error('Invalid answers: must be a valid DiagnosticAnswers object');
    }

    // Step 1: Compute raw embedding vector [a, b, c, ...]
    const embeddingVector = await computeEmbeddingVector(answers);

    // Step 1b: Use Logistic Regression classifier on embedding vector
    let logregPrediction;
    try {
      logregPrediction = await classifyWithLogisticRegression(embeddingVector);
    } catch (e) {
      throw e;
    }

    // Convert logistic regression predictions to score format for compatibility
    const embeddingScores = logregPrediction.predictions;

    // Step 3: Apply behavioral signal boosts if provided
    let finalScores = embeddingScores;
    if (context?.behavioralSignals) {
      finalScores = applyBehavioralSignalBoosts(embeddingScores, context.behavioralSignals);
    }

    // Step 4: Rank all types by final scores (high to low confidence)
    const rankedTypes = Object.entries(finalScores)
      .map(([type, score]) => ({
        type: type as StuckType,
        score: score * 10, // Scale to 0-10
        normalized: score, // Keep 0-1 for calibration
        reasons: ["Embedding-based diagnosis"],
      }))
      .sort((a, b) => b.score - a.score); // HIGH TO LOW

    const result = {
      primaryType: rankedTypes[0].type,
      confidence: rankedTypes[0].normalized,
      rankedTypes, // Ranked high → low (as per spec)
      summary: `Based on your responses, you seem primarily stuck with ${rankedTypes[0].type}. Tell us more so we can personalize next steps.`,
      embeddingSimilarities: embeddingScores, // For transparency
    };

    return result;
  } catch (e) {
    throw e;
  }
}

/**
 * Quick diagnostic using only embeddings (same as main function now)
 * Useful for fast fallback or testing
 */
export async function diagnoseWithEmbeddingsOnly(
  answers: DiagnosticAnswers,
  context?: DiagnosticContext,
): Promise<DiagnosisResult> {
  let scores = await computeEmbeddingScores(answers);

  if (context?.behavioralSignals) {
    scores = applyBehavioralSignalBoosts(scores, context.behavioralSignals);
  }

  const rankedTypes = Object.entries(scores)
    .map(([type, score]) => ({
      type: type as StuckType,
      score: score * 10,
      normalized: score,
      reasons: ["Embedding-based diagnosis (no Gemini refinement)"],
    }))
    .sort((a, b) => b.score - a.score);

  return {
    primaryType: rankedTypes[0].type,
    confidence: rankedTypes[0].normalized,
    rankedTypes,
    summary: `Based on your responses, you seem primarily stuck with ${rankedTypes[0].type}. 
Tell us more so we can personalize next steps.`,
    embeddingSimilarities: scores,
  };
}