import { TAB_LABELS } from "../constants";
import type { AppTab } from "../constants";

// Component that renders the navigation tabs for the app. It displays the available tabs and allows the user to switch between them. The navigation is only shown once the diagnostic process is complete.
/**
 * Interface NavigationProps defines the props for the Navigation component, which includes:
 * - activeTab: The currently active tab in the app, of type AppTab (which is a union of string literals representing each tab)
 * - onTabChange: A callback function that is called when the user clicks on a tab to change the active tab. It takes the new tab as an argument.
 * - processComplete: A boolean indicating whether the diagnostic process is complete. The navigation tabs will only be rendered if this is true.
 * 
 * Boilerplate code and styling for the Navigation component was generated by Claude Haiku 4.5 based on the following prompt:
 * 
 * Prompt: I am trying to design a navigation component for my app that allows users to switch between different tabs (Introduction, History, Insights, Intervention). 
 * The navigation should only be displayed once the diagnostic process is complete. Generate boilerplate code for me and styling using Tailwind CSS using the colors of our app.
 * 
 * All logic was implemented by the authors
 */
interface NavigationProps {
  activeTab: AppTab;
  onTabChange: (tab: AppTab) => void;
  processComplete: boolean;
}

export function Navigation({ activeTab, onTabChange, processComplete }: NavigationProps) {
  if (!processComplete) {
    return null;
  }

  return (
    <div className="rounded-2xl border border-emerald-900 bg-emerald-950/70 p-4">
      <div className="flex flex-wrap gap-2">
        {(Object.keys(TAB_LABELS) as AppTab[]).map((tabKey) => {
          const selected = activeTab === tabKey;

          return (
            <button
              key={tabKey}
              type="button"
              onClick={() => onTabChange(tabKey)}
              className={`rounded-lg border px-3 py-2 text-sm ${
                selected
                  ? "border-lime-300 bg-lime-300/20"
                  : "border-emerald-800 hover:border-lime-500"
              }`}
            >
              {TAB_LABELS[tabKey]}
            </button>
          );
        })}
      </div>
    </div>
  );
}
